/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex('tasks_table').del();
	await knex('tasks_table').insert([
		{
			task_name: 'DOCUMENT REVIEW',
			task_description: 'Review the intelligence report',
			task_requirement: 'Ensure confidentiality',
			creation_date: '2023-01-01 14:30:00',
			due_date: '2023-02-01 14:30:00',
			completion_date: '2023-01-25 14:30:00',
			is_active: false,
			assigned_to: 8,
			priority: 'Medium',
			assigned_by: 9,
		},
		{
			task_name: 'ENCRYPTION',
			task_description: 'Encrypt sensitive communications',
			task_requirement: 'Use military-grade algorithms',
			creation_date: '2023-02-05 14:30:00',
			due_date: '2023-03-07 14:30:00',
			completion_date: '2023-03-02 14:30:00',
			is_active: false,
			assigned_to: 6,
			priority: 'High',
			assigned_by: 7,
		},
		{
			task_name: 'OPERATION PLANNING',
			task_description: 'Plan the next strategic move',
			task_requirement: 'Consider all possible scenarios',
			creation_date: '2023-03-10 12:00:00',
			due_date: '2023-04-10 13:00:00',
			completion_date: '2023-04-05 13:00:00',
			is_active: false,
			assigned_to: 15,
			priority: 'High',
			assigned_by: 17,
		},
		{
			task_name: 'BRIEFING',
			task_description: 'Provide an update to the team',
			task_requirement: 'Include all recent developments',
			creation_date: '2023-04-15 14:30:00',
			due_date: '2023-05-16 14:30:00',
			completion_date: '2023-05-10 14:30:00',
			is_active: false,
			assigned_to: 7,
			priority: 'Medium',
			assigned_by: 11,
		},
		{
			task_name: 'EQUIPMENT AUDIT',
			task_description: 'Inspect and catalog all office equipment',
			task_requirement: 'Ensure everything meets protocol',
			creation_date: '2023-05-20 14:30:00',
			due_date: '2023-06-21 14:30:00',
			completion_date: '2023-06-15 14:30:00',
			is_active: false,
			assigned_to: 4,
			priority: 'Medium',
			assigned_by: 10,
		},
		{
			task_name: 'SECURITY DRILL',
			task_description: 'Execute a security practice drill',
			task_requirement: 'Ensure all staff participate',
			creation_date: '2023-06-25 14:30:00',
			due_date: '2023-07-26 14:30:00',
			completion_date: '2023-07-20 14:30:00',
			is_active: false,
			assigned_to: 3,
			priority: 'High',
			assigned_by: 6,
		},
		{
			task_name: 'DATA BACKUP',
			task_description: 'Backup all critical mission data',
			task_requirement: 'Use secure storage solutions',
			creation_date: '2023-07-30 14:30:00',
			due_date: '2023-08-31 14:30:00',
			completion_date: '2023-08-25 14:30:00',
			is_active: true,
			assigned_to: 6,
			priority: 'High',
			assigned_by: 12,
		},
		{
			task_name: 'INTELLIGENCE ANALYSIS',
			task_description: 'Analyze the latest field intelligence',
			task_requirement: 'Provide insights and potential threats',
			creation_date: '2023-08-20 14:30:00',
			due_date: '2023-10-02 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 11,
			priority: 'High',
			assigned_by: 13,
		},
		{
			task_name: 'COMMUNICATION SETUP',
			task_description: 'Set up secure communication lines',
			task_requirement: 'Test for any vulnerabilities',
			creation_date: '2023-08-30 14:30:00',
			due_date: '2023-10-16 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 10,
			priority: 'Medium',
			assigned_by: 12,
		},
		{
			task_name: 'TRAINING SESSION',
			task_description: 'Conduct a training session for new recruits',
			task_requirement: 'Cover basics of office protocol',
			creation_date: '2023-09-05 14:30:00',
			due_date: '2023-11-21 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 5,
			priority: 'Medium',
			assigned_by: 8,
		},
		{
			task_name: 'MISSION BRIEF',
			task_description: 'Brief the team on the next mission',
			task_requirement: 'Ensure clarity and confidentiality',
			creation_date: '2023-09-10 14:30:00',
			due_date: '2023-12-26 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 2,
			priority: 'High',
			assigned_by: 9,
		},
		{
			task_name: 'NETWORK MAINTENANCE',
			task_description: 'Maintain and update the internal network',
			task_requirement: 'Ensure no downtime during working hours',
			creation_date: '2023-08-10 14:30:00',
			due_date: '2023-10-10 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 5,
			priority: 'Medium',
			assigned_by: 6,
		},
		{
			task_name: 'SUPPLY CHECK',
			task_description: 'Check and reorder office supplies',
			task_requirement: 'Prioritize mission-critical items',
			creation_date: '2023-09-01 14:30:00',
			due_date: '2023-11-01 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 3,
			priority: 'Low',
			assigned_by: 5,
		},
		{
			task_name: 'FIELD REPORT',
			task_description: 'Compile reports from field agents',
			task_requirement: 'Ensure accuracy and detail',
			creation_date: '2023-09-15 14:30:00',
			due_date: '2023-11-15 14:30:00',
			completion_date: null,
			is_active: false,
			assigned_to: 2,
			priority: 'High',
			assigned_by: 4,
		},
		{
			task_name: 'DOCUMENT REDACTION',
			task_description: 'Redact sensitive information from reports',
			task_requirement: 'Follow protocol strictly',
			creation_date: '2023-09-20 14:30:00',
			due_date: '2023-12-01 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 7,
			priority: 'Medium',
			assigned_by: 9,
		},
		{
			task_name: 'CODE DECRYPTION',
			task_description: 'Decrypt messages received from field agents',
			task_requirement: 'Ensure confidentiality',
			creation_date: '2023-10-01 14:30:00',
			due_date: '2023-11-15 14:30:00',
			completion_date: null,
			is_active: false,
			assigned_to: 5,
			priority: 'High',
			assigned_by: 7,
		},
		{
			task_name: 'EQUIPMENT CALIBRATION',
			task_description: 'Calibrate communication devices',
			task_requirement: 'Minimize downtime',
			creation_date: '2023-10-10 14:30:00',
			due_date: '2023-11-01 14:30:00',
			completion_date: '2023-10-25 14:30:00',
			is_active: false,
			assigned_to: 3,
			priority: 'Medium',
			assigned_by: 5,
		},
		{
			task_name: 'OPERATION REVIEW',
			task_description: 'Review the success of the last operation',
			task_requirement: 'Provide constructive feedback',
			creation_date: '2023-10-15 14:30:00',
			due_date: '2023-12-10 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 12,
			priority: 'Medium',
			assigned_by: 15,
		},
		{
			task_name: 'SECURITY UPGRADE',
			task_description: 'Upgrade security protocols and systems',
			task_requirement: 'Train staff on new procedures',
			creation_date: '2023-11-01 14:30:00',
			due_date: '2023-12-15 14:30:00',
			completion_date: null,
			is_active: true,
			assigned_to: 10,
			priority: 'High',
			assigned_by: 14,
		},
		{
			task_name: 'CONFERENCE PREPARATION',
			task_description: 'Prepare for the upcoming military conference',
			task_requirement: 'Ensure all presentations are ready',
			creation_date: '2023-11-05 14:30:00',
			due_date: '2023-12-20 14:30:00',
			completion_date: null,
			is_active: false,
			assigned_to: 4,
			priority: 'Low',
			assigned_by: 6,
		},
	]);
};
